for_window [app_id="org.keepassxc.KeePassXC"] inhibit_idle fullscreen
for_window [app_id="com.borgbase.Vorta"] floating enable, resize set width 980 height 700
for_window [title="Picture-in-Picture"] floating enable, sticky enable, border pixel 2
assign [app_id="com.visualstudio.code"] workspace number 2
